### PR TITLE
Juno stop processing on block 9497172. FIX

### PR DESCRIPTION
**Pull request by web3cdnservices**
Added event: MsgCancelUnbondingDelegation on block 9497172.

```
2024-01-17T17:12:16.582Z <api-#2> ERROR Failed to decode message Error: Unregistered type url: /cosmos.staking.v1beta1.MsgCancelUnbondingDelegation
2024-01-17T17:12:16.659Z <Worker Service #2-#2> ERROR Failed to index block 9497172: Error: Unregistered type url: /cosmos.staking.v1beta1.MsgCancelUnbondingDelegation
```

@bz888 @jiqiang90 @jamesbayly

### CODE REVIEW

**Comment by web3cdnservices** [comment]
@jamesbayly 
Maybe it makes sense for me to synchronize the entire database myself? and not pour out every release into the world? After all, I think there will be many more requests. What are your thoughts on this?

**Comment by jiqiang90** [comment]
Hi @web3cdnservices nice work, it is working, thank you for the contribution

**Comment by jiqiang90** [comment]
> @jamesbayly Maybe it makes sense for me to synchronize the entire database myself? and not pour out every release into the world? After all, I think there will be many more requests. What are your thoughts on this?

It will be nice if you could continue contribute to the repo, the dictionary is important and might have impact other people using it, we really appreciate your help. We are happy to merge your requests

**Comment by web3cdnservices** [comment]
https://github.com/subquery/cosmos-subql-dictionaries/pull/25

@jiqiang90

**Pull request merged**
